name: nshealth-archive

on:
  schedule:
  - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Crawl and archive the results
        run: SEARCH_LIMIT=1 ./bin/crawl

      - uses: gr2m/create-or-update-pull-request-action@v1.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "Update data archive"
          body: "This pull request has been opened automatically."
          commit-message: "Update data archive"
          author: "Jeff Andersen <jeffandersen@gmail.com>"
